@ECHO OFF

SETLOCAL ENABLEDELAYEDEXPANSION
PUSHD "%~dp0"

CALL defines.bat

IF EXIST %BUILD_PATH% (
    ECHO Cleaning %BUILD_PATH%
    RMDIR /S /Q %BUILD_PATH%
)

IF EXIST %BIN_PATH% (
    ECHO Cleaning %BIN_PATH%
    RMDIR /S /Q %BIN_PATH%
)

IF EXIST %LIB_PATH% (
    ECHO Cleaning %LIB_PATH%
    RMDIR /S /Q %LIB_PATH%
)

SET ZIG_CACHE=..\.zig-cache
SET ZIG_OUT=..\zig-out

IF EXIST %ZIG_CACHE% (
    ECHO Cleaning %ZIG_CACHE%
    RMDIR /S /Q %ZIG_CACHE%
)

IF EXIST %ZIG_OUT% (
    ECHO Cleaning %ZIG_OUT%
    RMDIR /S /Q %ZIG_OUT%
)

POPD
ENDLOCAL
