@ECHO OFF

SETLOCAL ENABLEDELAYEDEXPANSION
PUSHD "%~dp0"

SET CMAKE_OPTIONS=

IF NOT "%GENERATOR%" == "" (
    SET CMAKE_OPTIONS=-G %GENERATOR%
)

SET CMAKE_OPTIONS=%CMAKE_OPTIONS% -S .. -B %BUILD_PATH% -DCMAKE_BUILD_TYPE=%CONFIGURATION%
SET CMAKE_OPTIONS=%CMAKE_OPTIONS% -DWITH_TESTS=%WITH_TESTS% -DBUILD_SHARED_LIBS=%BUILD_SHARED% -DNO_LIB=%NO_LIB% -DWITH_EXAMPLES=%WITH_EXAMPLES%

cmake %CMAKE_OPTIONS%

POPD
ENDLOCAL
